// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dona.Models;

#nullable disable

namespace dona.Migrations
{
    [DbContext(typeof(Datacontext))]
    [Migration("20240523170131_QUan")]
    partial class QUan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dona.Areas.Admin.Models.AdminMenu", b =>
                {
                    b.Property<long?>("AdminMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("AdminMenuID"));

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemLever")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("int");

                    b.Property<string>("ItemTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentLever")
                        .HasColumnType("int");

                    b.HasKey("AdminMenuID");

                    b.ToTable("AdminMenu");

                    b.HasData(
                        new
                        {
                            AdminMenuID = 1L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = false,
                            ItemLever = 0,
                            ItemName = "Dashboard",
                            ItemOrder = 1,
                            ParentLever = 0
                        },
                        new
                        {
                            AdminMenuID = 2L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = false,
                            ItemLever = 0,
                            ItemName = "Profile",
                            ItemOrder = 1,
                            ParentLever = 0
                        },
                        new
                        {
                            AdminMenuID = 3L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = false,
                            ItemLever = 0,
                            ItemName = "Directions",
                            ItemOrder = 2,
                            ParentLever = 0
                        },
                        new
                        {
                            AdminMenuID = 4L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = false,
                            ItemLever = 0,
                            ItemName = "Contact",
                            ItemOrder = 3,
                            ParentLever = 0
                        },
                        new
                        {
                            AdminMenuID = 5L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = false,
                            ItemLever = 0,
                            ItemName = "Log out",
                            ItemOrder = 4,
                            ParentLever = 0
                        },
                        new
                        {
                            AdminMenuID = 6L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            Icon = "bi bi-menu-button-wide",
                            IdName = "components-nav",
                            IsActive = true,
                            ItemLever = 1,
                            ItemName = "Post Management",
                            ItemOrder = 1,
                            ItemTarget = "components-nav",
                            ParentLever = 0
                        },
                        new
                        {
                            AdminMenuID = 7L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Post",
                            IsActive = true,
                            ItemLever = 2,
                            ItemName = "Update Post",
                            ItemOrder = 1,
                            ParentLever = 6
                        },
                        new
                        {
                            AdminMenuID = 8L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = true,
                            ItemLever = 2,
                            ItemName = "Approve and Publish Post",
                            ItemOrder = 2,
                            ParentLever = 6
                        },
                        new
                        {
                            AdminMenuID = 9L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = true,
                            ItemLever = 2,
                            ItemName = "Published Posts",
                            ItemOrder = 3,
                            ParentLever = 6
                        },
                        new
                        {
                            AdminMenuID = 10L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            Icon = "bi bi-journal-text",
                            IdName = "forms-nav",
                            IsActive = true,
                            ItemLever = 1,
                            ItemName = "Menu Management",
                            ItemOrder = 1,
                            ItemTarget = "forms-nav",
                            ParentLever = 0
                        },
                        new
                        {
                            AdminMenuID = 11L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Menu",
                            IsActive = true,
                            ItemLever = 2,
                            ItemName = "Add New Menu",
                            ItemOrder = 1,
                            ParentLever = 10
                        },
                        new
                        {
                            AdminMenuID = 12L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = true,
                            ItemLever = 2,
                            ItemName = "Edit Menu",
                            ItemOrder = 2,
                            ParentLever = 10
                        },
                        new
                        {
                            AdminMenuID = 13L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            Icon = "bi bi-bar-chart",
                            IdName = "charts-nav",
                            IsActive = true,
                            ItemLever = 1,
                            ItemName = "Slide Management ",
                            ItemOrder = 1,
                            ItemTarget = "charts-nav",
                            ParentLever = 0
                        },
                        new
                        {
                            AdminMenuID = 14L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = true,
                            ItemLever = 2,
                            ItemName = "Add New Slide",
                            ItemOrder = 1,
                            ParentLever = 13
                        },
                        new
                        {
                            AdminMenuID = 15L,
                            ActionName = "Index",
                            AreaName = "Admin",
                            ControllerName = "Home",
                            IsActive = true,
                            ItemLever = 2,
                            ItemName = "Edit Slide",
                            ItemOrder = 2,
                            ParentLever = 13
                        });
                });

            modelBuilder.Entity("dona.Model.viewPostMenu", b =>
                {
                    b.Property<long>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostID"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createted_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("PostID");

                    b.HasIndex("MenuID");

                    b.ToTable("viewPostMenu");

                    b.HasData(
                        new
                        {
                            PostID = 1L,
                            Abstract = "TFT UPDATE VERISON ",
                            Contents = "With 14.10 we asked ourselves, “What's not working?” and after reworking Lissandra, nerfing a few overperformers, and making Prismatic Orbs feel more like rare high rolls, we set out to make the not working stuff, well… work better.",
                            Images = "Image/anh1.jpg",
                            IsActive = true,
                            MenuID = 7,
                            MenuName = "Game UpDate",
                            PostOrder = 1,
                            Title = "TEAMFIGHT TACTICS PATCH 14.10 NOTES",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 2L,
                            Abstract = "We have quite a bit of stuff dropping in patch 14.10 ",
                            Contents = "We have quite a bit of stuff dropping in patch 14.10: Split 1 end and Split 2 start details",
                            Images = "Image/anh2.jpg",
                            IsActive = true,
                            MenuID = 7,
                            MenuName = "Game UpDate",
                            PostOrder = 2,
                            Title = "PATCH 14.10 NOTES",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 3L,
                            Images = "Image/anh3.jpg",
                            IsActive = true,
                            Link = "https://www.youtube.com/watch?v=oJl_MKDUHqU",
                            MenuID = 8,
                            MenuName = "EsPorts",
                            PostOrder = 3,
                            Title = "STAYING THE COURSE |MSI 2024",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 4L,
                            Images = "Image/anh4.jpg",
                            IsActive = true,
                            Link = "https://www.youtube.com/watch?v=8rPhx_W6YDE",
                            MenuID = 8,
                            MenuName = "EsPorts",
                            PostOrder = 4,
                            Title = "TOP 5 PLAYS|BRACKET STAGE WK1",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 5L,
                            Abstract = "In the beginning, the First Star gave birth to the universe and all life",
                            Contents = " To protect its creations and ensure the cycle of life would continue for eternity, the First Star entrusted individuals iron-willed and pure of heart with fragments of its essence—starlight—as protectors of the universe throughout the ages.",
                            Images = "Image/anh5.jpg",
                            IsActive = true,
                            MenuID = 9,
                            MenuName = "Lore",
                            PostOrder = 5,
                            Title = "PREVIOUSLY ON STAR GUARDIAN",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 6L,
                            Abstract = "Camavor is a brutal land with a bloody legacy",
                            Contents = " Kalista seeks to change that. When her young and narcissistic uncle, Viego, becomes king she vows to temper his destructive instincts as his loyal confidant, advisor, and military general.",
                            Images = "Image/anh6.jpg",
                            IsActive = true,
                            MenuID = 9,
                            MenuName = "Lore",
                            PostOrder = 6,
                            Title = "A LEAGUE OF LEGENDS NOVEL",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 7L,
                            Abstract = "There’s a lot going on for Pride this year across all our games",
                            Contents = "Pride content hits the Rift with Patch 14.11 and is available until Patch 14.12’s conclusion. The event brings a new mission and Pride Emote, “United,” featuring Twisted Fate and Neeko, as well as returning Pride emotes for 1 Blue Essence each—essence-ially free!",
                            Images = "Image/anh7.jpg",
                            IsActive = true,
                            MenuID = 10,
                            MenuName = "Community",
                            PostOrder = 7,
                            Title = "CELEBRATE PRIDE 2024: LEAGUE AND TFT",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 8L,
                            Abstract = "Calling all cosplayers, fan artists, and creators of all kinds",
                            Contents = "Calling all cosplayers, fan artists, and creators of all kinds! We've got a gallery of reference images for the champions featured in our latest cinematic",
                            Images = "Image/anh8.jpg",
                            IsActive = true,
                            MenuID = 10,
                            MenuName = "Community",
                            PostOrder = 8,
                            Title = "STILL HERE REFERENCE MATERIALS",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 9L,
                            Images = "Image/anh9.jpg",
                            IsActive = true,
                            Link = "https://www.youtube.com/watch?v=-KHMMMHvDdM",
                            MenuID = 6,
                            MenuName = "Riot Games",
                            PostOrder = 9,
                            Title = "THE MAGESEEKER : A LEAGUE OF  LEGENDS STORY GAMEPLAY",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 17, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 10L,
                            Images = "Image/anh10.jpg",
                            IsActive = true,
                            Link = "https://www.youtube.com/watch?v=n66QyujLXyg",
                            MenuID = 6,
                            MenuName = "Riot Games",
                            PostOrder = 10,
                            Title = "RIOT FORGE GAMES 2023|THE YEAR AHEAD",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 10, 17, 11, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("dona.Models.tblMenu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CotrollerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Levels")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuOrder")
                        .HasColumnType("int");

                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("MenuID");

                    b.ToTable("tblMenu");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            IsActive = true,
                            Levels = 1,
                            MenuName = "Home",
                            MenuOrder = 1,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 2,
                            IsActive = true,
                            Levels = 1,
                            MenuName = "Game",
                            MenuOrder = 2,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 3,
                            ActionName = "Index",
                            CotrollerName = "Champions",
                            IsActive = true,
                            Levels = 1,
                            MenuName = "Champions",
                            MenuOrder = 3,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 4,
                            IsActive = true,
                            Levels = 1,
                            MenuName = "New",
                            MenuOrder = 4,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 5,
                            IsActive = true,
                            Levels = 1,
                            MenuName = "About as",
                            MenuOrder = 6,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 6,
                            IsActive = true,
                            Levels = 2,
                            MenuName = "Riot Games",
                            MenuOrder = 1,
                            ParentID = 4,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 7,
                            IsActive = true,
                            Levels = 2,
                            MenuName = "Game UpDate",
                            MenuOrder = 2,
                            ParentID = 4,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 8,
                            IsActive = true,
                            Levels = 2,
                            MenuName = "EsPorts",
                            MenuOrder = 3,
                            ParentID = 4,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 9,
                            IsActive = true,
                            Levels = 2,
                            MenuName = "Lore",
                            MenuOrder = 4,
                            ParentID = 4,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 10,
                            IsActive = true,
                            Levels = 2,
                            MenuName = "Community",
                            MenuOrder = 5,
                            ParentID = 4,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 11,
                            IsActive = true,
                            Levels = 2,
                            MenuName = "Merch",
                            MenuOrder = 6,
                            ParentID = 4,
                            Position = 1
                        });
                });

            modelBuilder.Entity("dona.Models.tblPost", b =>
                {
                    b.Property<long>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostID"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<int>("PostOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createted_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("PostID");

                    b.ToTable("tblPost");

                    b.HasData(
                        new
                        {
                            PostID = 1L,
                            Images = "images1/anh1.jpg",
                            IsActive = true,
                            Link = "https://www.youtube.com/watch?v=gicjDRPN-5E",
                            MenuID = 7,
                            PostOrder = 1,
                            Title = "The Unlock | Xbox Game Pass",
                            author = "oai",
                            createted_Date = new DateTime(2024, 6, 10, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 2L,
                            Images = "images1/anh2.jpg",
                            IsActive = true,
                            Link = "https://www.riotgames.com/en/news/now-streaming-on-riot-mobile",
                            MenuID = 7,
                            PostOrder = 2,
                            Title = "Now Streaming on Riot Mobile",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 12, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostID = 3L,
                            Images = "images1/anh3.jpg",
                            IsActive = true,
                            Link = "https://www.riotgames.com/en/news/link-riot-account-to-xbox-game-pass",
                            MenuID = 7,
                            PostOrder = 3,
                            Title = "Link Riot Account with Xbox Game Pass Today to Unlock Benefits",
                            author = "oai",
                            createted_Date = new DateTime(2024, 5, 12, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("dona.Model.viewPostMenu", b =>
                {
                    b.HasOne("dona.Models.tblMenu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
