// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dona.Models;

#nullable disable

namespace dona.Migrations
{
    [DbContext(typeof(Datacontext))]
    [Migration("20240515070205_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dona.Models.tblMenu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CotrollerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Levers")
                        .HasColumnType("int");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuOrder")
                        .HasColumnType("int");

                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("MenuID");

                    b.ToTable("tblMenu");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            IsActive = true,
                            Levers = 1,
                            MenuName = "Home",
                            MenuOrder = 1,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 2,
                            IsActive = true,
                            Levers = 1,
                            MenuName = "Game",
                            MenuOrder = 2,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 3,
                            IsActive = true,
                            Levers = 1,
                            MenuName = "Play",
                            MenuOrder = 3,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 4,
                            IsActive = true,
                            Levers = 1,
                            MenuName = "New",
                            MenuOrder = 4,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 5,
                            IsActive = true,
                            Levers = 1,
                            MenuName = "Blog",
                            MenuOrder = 5,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 6,
                            IsActive = true,
                            Levers = 1,
                            MenuName = "About as",
                            MenuOrder = 6,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 7,
                            IsActive = true,
                            Levers = 1,
                            MenuName = "pages",
                            MenuOrder = 7,
                            ParentID = 0,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 8,
                            IsActive = true,
                            Levers = 2,
                            MenuName = "contact",
                            MenuOrder = 1,
                            ParentID = 6,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 9,
                            IsActive = true,
                            Levers = 2,
                            MenuName = "blog",
                            MenuOrder = 2,
                            ParentID = 6,
                            Position = 1
                        },
                        new
                        {
                            MenuID = 10,
                            IsActive = true,
                            Levers = 2,
                            MenuName = "acount",
                            MenuOrder = 3,
                            ParentID = 6,
                            Position = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
